name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Ensure this matches your project requirements

      - name: Install dependencies
        run: |
          npm install
          npx playwright install

      - name: Run Playwright tests
        run: npx playwright test
        continue-on-error: true # Continue even if there are test failures

      - name: Deploy Playwright report to GitHub Pages
        if: always() # Ensure this step runs regardless of test results
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
          publish_dir: ./playwright-report
          publish_branch: gh-pages
